server:
  port: 8001

  servlet:
    context-path: /admin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yin12306?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

knife4j:
  enable: true
  openapi:
    title: yin12306
    description: "`我是文档`,**你知道吗**"
    email: yin82347331
    concat: yin
    url: https://docs.xiaominfo.com
    version: v1.0
    license: 党和人民
    license-url: www.***.com
    terms-of-service-url: https://***.com/
    group:
      test1:
        group-name: 分组名称1
        api-rule: package
        api-rule-resources:
          - org.yin.controller
#          - org.example.controller

mybatis-plus:
  # 多包名使用 例如 com.xzsy.**.mapper,com.xxx.**.mapper
  mapperPackage: org.yin.**.mapper
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.yin.domain

  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  checkConfigLocation: false
  configuration:
    # 自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    # MyBatis 自动映射策略
    # NONE：不启用 PARTIAL：只对非嵌套 resultMap 自动映射 FULL：对所有 resultMap 自动映射
    autoMappingBehavior: FULL
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
    autoMappingUnknownColumnBehavior: NONE
    # 更详细的日志输出 会有性能损耗 org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭日志记录 (可单纯使用 p6spy 分析) org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 默认日志输出 org.apache.ibatis.logging.slf4j.Slf4jImpl
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 是否打印 Logo banner
    banner: true
    dbConfig:
      logic-delete-field: deleted # 全局逻辑删除字段名
      logicDeleteValue: 1 # 逻辑已删除值
      logicNotDeleteValue: 0 # 逻辑未删除值
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      idType: ASSIGN_ID
      insertStrategy: NOT_NULL
      updateStrategy: NOT_NULL
      whereStrategy: NOT_NULL
